###
POST http://localhost:8000/create_order
Content-Type: application/json

{
  "user_id": 1,
  "product_ids": [1, 2, 3]
}

###
POST http://localhost:8000/get_orders
Content-Type: application/json

{
  "user_id": 1
}

###
POST http://localhost:8000/get_order
Content-Type: application/json

{
  "order_id": "df766840-8f70-4fff-bce2-427b7e1a7678"
}